"""add gateway analytics

Revision ID: 6ac2fa6b5b9b
Revises: 3b29a87f75f1
Create Date: 2026-07-01 22:28:56.842017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac2fa6b5b9b'
down_revision: Union[str, Sequence[str], None] = '3b29a87f75f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
